<a href="https://colab.research.google.com/github/s92c27/AI/blob/master/numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
np.array([range(i, i + 3) for i in [2, 4, 6]])


array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [4]:
np.tile(np.array([[1,2],[6,7]]),3)


array([[1, 2, 1, 2, 1, 2],
       [6, 7, 6, 7, 6, 7]])

In [5]:
np.tile(np.array([[1,2],[6,7]]),(2,2))


array([[1, 2, 1, 2],
       [6, 7, 6, 7],
       [1, 2, 1, 2],
       [6, 7, 6, 7]])

In [6]:
import numpy as np
np.array([range(i, i + 3) for i in [2, 4, 6]])


array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])